### ISSUE TITLE
Support AdditionalFiles in WithAnalyzers

### ISSUE THREAD

**Issue by jerone** [cezarypiatek/RoslynTestKit#24]
For testing purposes I want to define my own `AdditionalFiles` and `AdditionalDocuments`.

It appears to be possible via [`DiagnosticAnalyzerExtensions.WithAnalyzers`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.diagnostics.diagnosticanalyzerextensions.withanalyzers?view=roslyn-dotnet-4.7.0) method, third parameter `analysisOptions`, property [`AnalyzerOptions.AdditionalFiles`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.diagnostics.analyzeroptions.additionalfiles?view=roslyn-dotnet-4.7.0#microsoft-codeanalysis-diagnostics-analyzeroptions-additionalfiles).
See https://stackoverflow.com/a/34052279/108448

Would it be possible to support this feature...

**Comment by cezarypiatek** [comment]
The API has been extended to allow for providing additional files
https://github.com/cezarypiatek/RoslynTestKit/blob/master/src/RoslynTestKit/BaseTestFixture.cs#L19

sample usage

```cs
[Test]
public void should_verify_analyzer()
{
    var fixture = RoslynFixtureFactory.Create<SampleAnalyzer>(new () {
        AdditionalFiles= new []{
            new AnalyzerAdditionalFile("my_settings_file.json")
        };
    });

    //TODO: test your analyzer
}
```

**Comment by jerone** [comment]
This looks like exactly what was needed. Thanks.
