### ISSUE TITLE
Readme - Examples Outdated?

### ISSUE THREAD

**Issue by broderickt2** [cezarypiatek/RoslynTestKit#28]
I was following along the 2nd listed example as shown below and cannot find the methods: `CreateDocumentFromMarkup`, `GetMarkerLocation`. I found `CreateDocumentFromCode` exists but this lives in the abstract class `BaseTestFixture`. Assuming this is the correct method, this cannot be called so easily.

```
[Test]
public void AutoPropDeclaredAndUsedInConstructor()
{
    const string markup = @"
class C
{
	public bool MyProperty { get; [|private set;|] }
	public C(bool f)
	{
		MyProperty = f;
	}
}";

    var fixture = RoslynFixtureFactory.Create<UseGetterOnlyAutoPropertyAnalyzer>();

    var document = this.CreateDocumentFromMarkup(markup, "MySampleProject", "MySampleDocument");
    var diagnosticLocation = this.GetMarkerLocation(markup);
    fixture.HasDiagnostic(document, DiagnosticIds.UseGetterOnlyAutoProperty, diagnosticLocation);
}
```

**Comment by cezarypiatek** [comment]
Yes, that seems to be outdated and it looks like the ability to override the project and document names has been removed. Do you need such a feature? What's your use case?

**Comment by broderickt2** [comment]
I don't need this feature. More specifically what I was trying to do is described in [issue 29](https://github.com/cezarypiatek/RoslynTestKit/issues/29); I wanted 2 classes in the code block. When I saw this code example, I was trying to setup a document and then add the 2 classes but then found this method did not exist which confused me.

**Comment by broderickt2** [comment]
Closing this out for now. Takeaway, the readme could have its examples updated if you get a moment. Thanks!
